services:
  - type: web
    name: resqnet-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 5000
